Created At: 2026-06-05T10:42:16Z
Completed At: 2026-06-05T10:42:16Z
File Path: `file:///Users/chaser/code/focus-oasis/src/components/canvas/Plant.tsx`
Total Lines: 2
Total Bytes: 2071
Showing lines 1 to 2
The following code has been modified to include a line number before every line, in the format: <line_number>: <original_line>. Please note that any changes targeting the original code should remove the line number, colon, and leading space.
1: "import { useRef, useMemo } from 'react';\nimport { useFrame } from '@react-three/fiber';\nimport * as THREE from 'three';\nimport gsap from 'gsap';\nimport { useGSAP } from '@gsap/react';\nimport { useTimerStore } from '../../store/useTimerStore';\n\ngsap.registerPlugin(useGSAP);\n\nconst seededRandom = (seed: number) => {\n  const x = Math.sin(seed++) * 10000;\n  return x - Math.floor(x);\n};\n\n// Generates an ethereal tree structure\nconst generateBranches = (depth: number, maxDepth: number, parentLength: number, seed: number): any => {\n  if (depth > maxDepth) return null;\n  \n  const length = parentLength * (0.7 + seededRandom(seed) * 0.2);\n  const radiusBottom = depth === 0 ? length * 0.15 : parentLength * 0.05;\n  const radiusTop = length * 0.03;\n  const branches = [];\n  \n  if (depth < maxDepth) {\n    const numChildren = depth === 0 ? 3 : 2 + Math.floor(seededRandom(seed + depth) * 2);\n    for (let i = 0; i < numChildren; i++) {\n      const childSeed = seed + depth * 10 + i;\n      branches.push({\n        angleY: (i / numChildren) * Math.PI * 2 + (seededRandom(childSeed) * 0.5),\n        angleZ: Math.PI / 6 + (seededRandom(childSeed + 1) * 0.3),\n        children: generateBranches(depth + 1, maxDepth, length, childSeed + 2)\n      });\n    }\n  }\n\n  return { length, radiusBottom, radiusTop, branches, seed };\n};\n\nconst BranchNode = ({ data, depth = 0, isDead = false }: { data: any, depth?: number, isDead: boolean }) => {\n  const meshRef = useRef<THREE.Group>(null);\n  const crystalRef = useRef<THREE.Mesh>(null);\n  const branchMaterialRef = useRef<THREE.MeshStandardMaterial>(null);\n  const crystalMaterialRef = useRef<THREE.MeshPhysicalMaterial>(null);\n  const crystalFloatY = useRef(0);\n  \n  const isLeaf = !data.branches || data.branches.length === 0;\n\n  useGSAP(() => {\n    if (isDead) {\n      if (crystalRef.current) {\n        // Crystals shatter / fall down\n        gsap.to(crystalRef.current.position, {\n          y: -data.length - depth,\n          x: (Math.random() - 0.5) * 2,\n 
2: <truncated 4688 bytes>
The above content shows the entire, complete file contents of the requested file.
